### ISSUE TITLE
Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by IceQ1337** [IceQ1337/OverwatchChecker#8]
btw this message always comes up but only sometimes it crases cmd randomly anyway to fix that?

(node:2856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

_Originally posted by @45656456kawai in https://github.com/IceQ1337/OverwatchChecker/issues/7#issuecomment-569306941_

**Comment by IceQ1337** [comment]
@45656456kawai, i have made several adjustments to the script and https://github.com/IceQ1337/OverwatchChecker/commit/b8820afa546f4ea8b949cc80197145b0b7cc47b5 has most-likely fixed the issue, but i've also made two other changes that may be causing the script to stop working.

Unfortunately, I am currently unable to test the script myself, so I would ask you to check whether the current version still works and whether any errors occur. I recommend saving the old version until you are sure that the new one works.

**Comment by 45656456kawai** [comment]
Alright testing now

**Comment by 45656456kawai** [comment]
Okay, so it didn't crash this time but stopped after an hour or so.

> csgo-overwatch-checker@1.1.0 start C:\Users\private\Desktop\OW TEST
> node server.js

Error: GC Connection Timeout
    at Timeout._onTimeout (C:\Users\private\Desktop\OW TEST\utility\GameCoordinator.js:66:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Error: Failed To Send Message: Timeout
    at Timeout._onTimeout (C:\Users\private\Desktop\OW TEST\utility\GameCoordinator.js:154:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:3416) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ranking' of undefined
    at SteamUser.<anonymous> (C:\Users\private\Desktop\OW TEST\server.js:230:32)
(node:3416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: Cannot read property '0' of undefined
    at f (C:\Users\private\Desktop\OW TEST\node_modules\unbzip2-stream\lib\bit_iterator.js:30:34)
    at Object.bzip2.decompress (C:\Users\private\Desktop\OW TEST\node_modules\unbzip2-stream\lib\bzip2.js:283:28)
    at decompressBlock (C:\Users\private\Desktop\OW TEST\node_modules\unbzip2-stream\index.js:30:29)
    at decompressAndQueue (C:\Users\private\Desktop\OW TEST\node_modules\unbzip2-stream\index.js:47:20)
    at Stream.end (C:\Users\private\Desktop\OW TEST\node_modules\unbzip2-stream\index.js:82:17)
    at _end (C:\Users\private\Desktop\OW TEST\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\Users\private\Desktop\OW TEST\node_modules\through\index.js:74:5)
    at ReadStream.onend (_stream_readable.js:687:10)
    at Object.onceWrapper (events.js:297:20)
    at ReadStream.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! csgo-overwatch-checker@1.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the csgo-overwatch-checker@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\private\AppData\Roaming\npm-cache\_logs\2019-12-28T19_06_12_880Z-debug.log
PS C:\Users\private\Desktop\OW TEST>

**Comment by IceQ1337** [comment]
The "GC Connection Timeout" error doesn't come directly from the script itself, but from now on, the affected account should log out to prevent any errors like this. I don't know if the second part is also caused by this, but we will see.

**Comment by 45656456kawai** [comment]
The second try ran over 10 hours without any problem.

**Comment by IceQ1337** [comment]
All right, thank you for your efforts. If there is any problem, just report it again.
